name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install, build
        run: |
          yarn
          yarn audit
          yarn build
        env:
          CI: true
